### ISSUE TITLE
Link to DCC++EX

### ISSUE THREAD

**Issue by FrightRisk** [lucadentella/BoosterBoard#1]
Hello Luca. You may want to replace your links for DCC++ with DCC++EX. The old DCC++ has been abandoned since 2014. EX has been around for 2 years now and while it is a complete rewrite, it uses the same <DCC++> command language. There are many significant improvements. Our website is here:

https://dcc-ex.com/

and Discord server here:

https://discord.gg/PuPnNMp8Qf

**Comment by lucadentella** [comment]
Hi 

thanks for the suggestion... In my first tutorial I covered DCC++ as I found it's still very adopted in many DIY model layouts.
In a future tutorial I'll cover for sure your great projects and the improvements you made to the original code!
